version: '2'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=birdbook
    volumes:
      - 'pgdata:/data/postgres'

volumes:
  pgdata:
    driver: local
